# Generated by Django 5.0.7 on 2024-07-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('speed', models.FloatField(default=0.0)),
                ('duration', models.FloatField(default=0.0)),
            ],
        ),
    ]
